### ISSUE TITLE
...extraEntry语法错

### ISSUE THREAD

**Issue by llg3footcat** [tyaqing/mogo-h5plus#1]
我npm start的时候，报这个语法错，这个是es6的语法。我需要怎么配置呀。
webpack.config.js:37    
...extraEntry
    ^^^
SyntaxError: Unexpected token ...

**Comment by tyaqing** [comment]
请提供下你安装的node版本

**Comment by tyaqing** [comment]
@llg3footcat  你已经解决这个问题了么

**Comment by llg3footcat** [comment]
我用的是node v6.0.0的版本，我把版本升级下试试,多谢。很期待你的项目，希望能多加入点5+和mui的内容。

**Comment by tyaqing** [comment]
好的,node升级到最新版就可以了

**Comment by manfengjun** [comment]
node 10.6.0  报这个错是什么问题
Syntax Error: Unexpected token (93:2)

  91 |
  92 | const Props = {
> 93 |   ...props(),
     |   ^
  94 |   title: {
  95 |     type: String,
  96 |     required: true
