### ISSUE TITLE
Syntax Error: Unexpected token (93:2)

### ISSUE THREAD

**Issue by manfengjun** [tyaqing/mogo-h5plus#10]
node 10.6.0 报这个错是什么问题
Syntax Error: Unexpected token (93:2)
const Props = {

...props(),
 ^
title: {
type: String,
required: true

**Comment by tyaqing** [comment]
请问在什么地方使用呢,解构应该是没有问题的.也是测试过的

**Comment by manfengjun** [comment]
npm start的时间就报这个错，好多个文件
