### ISSUE TITLE
工具函数中的fire函数是否必须要先引入mui？

### ISSUE THREAD

**Issue by NinjaJin** [tyaqing/mogo-h5plus#11]
webview.evalJS(
        "typeof mui!=='undefined'&&mui.receive('" +
          eventType +
          "'," +
          data +
          ")"
      );
看这个写法好像是必须mui!=='undefined'才能用，别不用引mui也能跨页面监听的方法吗

**Comment by tyaqing** [comment]
稍等,1.1.0会加入示例
