### ISSUE TITLE
页面多了以后，编译速度特别慢

### ISSUE THREAD

**Issue by NinjaJin** [tyaqing/mogo-h5plus#12]
页面多了以后（40多个页面），编译速度特别慢。vue文件修改一下编译就得起码2分钟，而且很大概率奔溃报错。非常影响开发，希望可以改善

**Comment by tyaqing** [comment]
不要频繁修改pagejson就行了,其他的我会删掉一些不需要的插件

**Comment by NinjaJin** [comment]
没有修改pagejson，就改vue页面，一样编译极慢且报错
