### ISSUE TITLE
需求收集表

### ISSUE THREAD

**Issue by tyaqing** [tyaqing/mogo-h5plus#13]
如果你对项目有更好的建议请在此处提出.

**Comment by NinjaJin** [comment]
跪求解决编译速度慢及奔溃的问题。不然根本无法调试呀😢
机子为17款中配macpro

**Comment by 593496637** [comment]
调用h5+ api 可以直接调试么。

**Comment by SweetJun** [comment]
想知道怎么控制返回，比如执行一个方法，返回上两层webview。。。

**Comment by tyaqing** [comment]
@SweetJun  下次直接开新issue吧,规范点.
直接关闭掉2个webview就可以了

**Comment by 715476864** [comment]
想办法把vuex也搞进来吧。放应用需要在前端维护一些基础数据时只依靠localstorage或localsession确实显得有些麻烦。
