### ISSUE TITLE
打开webview的时候速度特别慢。

### ISSUE THREAD

**Issue by NinjaJin** [tyaqing/mogo-h5plus#17]
不管是plus.webview.create还是plus.webview.open，页面内容渲染的速度都很慢，
我在考虑会不会受这几个原因影响：
1.我使用的vuex
2.我的webview没有使用原生titleNView，都是写在各个页面中
3.我的一些ajax数据加载写在created生命周期中，使用axios，用async await来处理异步
请问上面的这几个原因会导致非常严重的性能问题吗？或者是其他原因导致的？因为我的页面渲染速度真的是慢到有点不能接受，用户体验极差，比你的demo慢很多。
PS：相同页面打开过一次，第二次打开会快一些

**Comment by tyaqing** [comment]
看1.2的案例吧,几个打开webview的方式可以按需求使用

**Comment by NinjaJin** [comment]
@tyaqing 看过也都使用过。我的问题不在于页面打开速度，而在于页面渲染速度，打开很快但是白屏渲染很久才出来内容

**Comment by tyaqing** [comment]
@NinjaJin 页面不要加载太多东西,复杂的 页面最好不要使用ui框架,
