### ISSUE TITLE
请问路由openWebview中的html地址是怎么来的。

### ISSUE THREAD

**Issue by NinjaJin** [tyaqing/mogo-h5plus#2]
openWebview(
        {
          url: "./map/map.html",
          id: "./map/map.html"
        },
        {
          bounce: "none"
        }
      );
::: tip 路由
遵循相对路径原则,如果在`src`访问这个页面则就是`./goods/list.html`
!!! 后缀一定是`.html`
:::
tip没看懂，这个路径和这个html是怎么得出的

**Comment by NinjaJin** [comment]
是用html-webpack-plugin这个插件生成的吗

**Comment by tyaqing** [comment]
@NinjaJin  是html-webpack-plugin生成的入口文件
