### ISSUE TITLE
tabBar的页面切换该怎么做？

### ISSUE THREAD

**Issue by NinjaJin** [tyaqing/mogo-h5plus#4]
打开新的窗口可以用openWebview，首页的tabbar导航切换用什么呢？
ps:  detail.vue中的路由操作有点模棱两可，没配置路由，点击也没反应
    onClickCart() {
      this.$router.push("cart");
    },

**Comment by tyaqing** [comment]
@NinjaJin  不需要用router ,只要用v-show就可以了,根据tab的key来切换显示的视图
